# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-22 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20171222_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='created_at',
            new_name='create_dt',
        ),
        migrations.AddField(
            model_name='relation',
            name='status',
            field=models.CharField(choices=[('F', 'Friend'), ('B', 'Break'), ('R', 'Reject')], default='F', max_length=1),
        ),
    ]
