#!/bin/bash

NAME="simplesns"
DIR=/home/simplesns/simpleMenu
USER=simplesns
GROUP=simplesns
WORKERS=3
BIND=unix:/home/simplesns/run/gunicorn.sock
DJANGO_SETTINGS_MODULE=simpleMenu.settings
DJANGO_WSGI_MODULE=simpleMenu.wsgi
LOG_LEVEL=error

cd $DIR
source ../venv/bin/activate

export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DIR:$PYTHONPATH

exec ../venv/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $WORKERS \
  --user=$USER \
  --group=$GROUP \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --log-file=-