# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-30 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='taken_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
