# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-03 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171130_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.FileField(upload_to='contents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='lat',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='lng',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
