# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-22 09:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20171221_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucket',
            old_name='created_at',
            new_name='create_dt',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='created_dt',
            new_name='create_dt',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='created_at',
            new_name='create_dt',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_dt',
            new_name='create_dt',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='created_dt',
            new_name='create_dt',
        ),
        migrations.AddField(
            model_name='post',
            name='bucket_user_set',
            field=models.ManyToManyField(blank=True, related_name='bucket_user_set', through='blog.Bucket', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.Post'),
        ),
    ]
