# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-22 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171222_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='create_user',
            new_name='author',
        ),
    ]
