# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-22 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20171222_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='status',
            field=models.CharField(choices=[('P', 'Public'), ('V', 'Private')], default='P', max_length=1),
        ),
    ]
