# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-23 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_theme_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='tags',
            new_name='tag_set',
        ),
    ]
